# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: quantcdn/cli:latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install the dependencies
        run: npm i

      - name: Build the application
        run: npm run build
        
      - name: INFO
        uses: docker://quantcdn/cli:latest
        env:
          QUANT_TOKEN: ${{ secrets.QUANT_TOKEN }}
        with:
          entrypoint: quant
          args: info -c quant -p gatsby-actions-example -t $QUANT_TOKEN

      - name: INFO
        uses: docker://quantcdn/cli:latest
        with:
          entrypoint: sh
          args: ls /github/workspace

      - name: Print build artefacts
        run: echo $PWD && ls -la

      - name: Quant info
        env:
          QUANT_TOKEN: ${{ secrets.QUANT_TOKEN }}
        run: quant info -c quant -p gatsby-actions-example -t $QUANT_TOKEN
        
      - name: Deploy with Quant!
        env:
          QUANT_TOKEN: ${{ secrets.QUANT_TOKEN }}
        run: quant deploy $PWD/public -c quant -p gatsby-actions-example -t $QUANT_TOKEN

